postgres:
    image: postgres
    ports:
        - 5433:5432
    volumes:
        - ../ckan/bin/postgres_init:/docker-entrypoint-initdb.d/
        - ./postgres-data:/tmp/postgres-data
    environment:
        - CKAN_POSTGRES_DB=stcndm_ckan
        - CKAN_POSTGRES_USER=stcndm_usr
        - CKAN_POSTGRES_PWD=pass
        - CKAN_DATASTORE_POSTGRES_DB=stcndm_ckan_datastore
        - CKAN_DATASTORE_POSTGRES_WRITE_USER=stcndm_usr
        - CKAN_DATASTORE_POSTGRES_READ_USER=datastore_stcndm_usr
        - CKAN_DATASTORE_POSTGRES_READ_PWD=pass
