#!/bin/sh
psql -U postgres -c "CREATE USER ${CKAN_POSTGRES_USER} \
    WITH PASSWORD '${CKAN_POSTGRES_PWD}' \
    NOSUPERUSER NOCREATEDB NOCREATEROLE;"

psql -U postgres -c "CREATE USER ${CKAN_DATASTORE_POSTGRES_USER} \
    WITH PASSWORD '${CKAN_DATASTORE_POSTGRES_PWD}' \
    NOSUPERUSER NOCREATEDB NOCREATEROLE;"

createdb -U postgres -O ${CKAN_POSTGRES_USER} ${CKAN_DB} -E utf-8
createdb -U postgres -O ${CKAN_POSTGRES_USER} ${CKAN_DATASTORE_DB} -E utf-8
